#!/usr/bin/env python3
"""Back-project saved DA3 depth maps into a colored PLY point cloud.

Examples
--------
# Validate depth + intrinsics for one frame in that camera's coordinate system.
python backproject_da3.py --frames 0 --camera-space \
    --output runs/rgb_da3_small/frame_000000_camera.ply

# Validate depth + intrinsics + extrinsics using all frames (about 5.5M points).
python backproject_da3.py --frames all --pixel-stride 2 \
    --output runs/rgb_da3_small/fused_stride2.ply

# Export every valid pixel from every frame (about 21.7M points; large file).
python backproject_da3.py --frames all --pixel-stride 1 \
    --output runs/rgb_da3_small/fused_full.ply
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


VERTEX_DTYPE = np.dtype(
    [
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("red", "u1"),
        ("green", "u1"),
        ("blue", "u1"),
    ]
)


def parse_frames(spec: str, frame_count: int) -> list[int]:
    """Parse 'all', '0,3,7', or inclusive ranges such as '10-20'."""
    if spec.strip().lower() == "all":
        return list(range(frame_count))

    selected: set[int] = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            start_text, end_text = part.split("-", maxsplit=1)
            start, end = int(start_text), int(end_text)
            if end < start:
                raise ValueError(f"Invalid descending frame range: {part}")
            selected.update(range(start, end + 1))
        else:
            selected.add(int(part))

    frames = sorted(selected)
    if not frames:
        raise ValueError("No frames selected")
    if frames[0] < 0 or frames[-1] >= frame_count:
        raise ValueError(f"Frame selection must be within 0..{frame_count - 1}")
    return frames


def as_homogeneous(extrinsic: np.ndarray) -> np.ndarray:
    if extrinsic.shape == (4, 4):
        return extrinsic
    if extrinsic.shape == (3, 4):
        matrix = np.eye(4, dtype=np.float64)
        matrix[:3, :4] = extrinsic
        return matrix
    raise ValueError(f"Expected a 3x4 or 4x4 extrinsic, got {extrinsic.shape}")


def valid_mask(
    depth: np.ndarray,
    confidence: np.ndarray,
    confidence_threshold: float | None,
    max_depth: float | None,
) -> np.ndarray:
    valid = np.isfinite(depth) & (depth > 0)
    if confidence_threshold is not None:
        valid &= np.isfinite(confidence) & (confidence >= confidence_threshold)
    if max_depth is not None:
        valid &= depth <= max_depth
    return valid


def write_header(handle, vertex_count: int) -> None:
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Generated by backproject_da3.py\n"
        f"element vertex {vertex_count}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        "end_header\n"
    )
    handle.write(header.encode("ascii"))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Back-project DA3 depth, intrinsics, and extrinsics to a colored PLY."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path("runs/rgb_da3_small/npy"),
        help="Directory containing depth.npy, conf.npy, intrinsics.npy, and extrinsics.npy.",
    )
    parser.add_argument(
        "--prediction-npz",
        type=Path,
        default=Path("runs/rgb_da3_small/exports/npz/results.npz"),
        help="DA3 NPZ containing the processed RGB array under the 'image' key.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("runs/rgb_da3_small/fused_stride2.ply"),
    )
    parser.add_argument(
        "--frames",
        default="all",
        help="Frames to export: 'all', comma-separated indices, or ranges such as '0-20'.",
    )
    parser.add_argument(
        "--pixel-stride",
        type=int,
        default=2,
        help="Use every Nth pixel in x and y. Use 1 for every pixel (default: 2).",
    )
    parser.add_argument(
        "--confidence-percentile",
        type=float,
        default=None,
        help="Optional global confidence percentile to retain; omitted means no confidence filtering.",
    )
    parser.add_argument(
        "--max-depth",
        type=float,
        default=None,
        help="Optional maximum predicted depth to retain.",
    )
    parser.add_argument(
        "--camera-space",
        action="store_true",
        help="Do not apply extrinsics. This is only valid when exactly one frame is selected.",
    )
    parser.add_argument(
        "--intrinsics",
        type=Path,
        default=None,
        help="Optional replacement intrinsics .npy with shape (3,3) or (N,3,3).",
    )
    args = parser.parse_args()

    if args.pixel_stride < 1:
        parser.error("--pixel-stride must be at least 1")
    if args.confidence_percentile is not None and not 0 <= args.confidence_percentile <= 100:
        parser.error("--confidence-percentile must be between 0 and 100")

    depth = np.load(args.data_dir / "depth.npy", mmap_mode="r")
    confidence = np.load(args.data_dir / "conf.npy", mmap_mode="r")
    predicted_intrinsics = np.load(args.data_dir / "intrinsics.npy")
    extrinsics = np.load(args.data_dir / "extrinsics.npy")
    with np.load(args.prediction_npz) as archive:
        images = archive["image"]

    if depth.shape != confidence.shape:
        raise ValueError(f"Depth {depth.shape} and confidence {confidence.shape} do not match")
    if images.shape[:3] != depth.shape:
        raise ValueError(f"Images {images.shape} and depth {depth.shape} do not match")

    frame_count, height, width = depth.shape
    frames = parse_frames(args.frames, frame_count)
    if args.camera_space and len(frames) != 1:
        parser.error("--camera-space requires exactly one selected frame")

    if args.intrinsics is None:
        intrinsics = predicted_intrinsics
        intrinsics_source = str(args.data_dir / "intrinsics.npy")
    else:
        intrinsics = np.load(args.intrinsics)
        if intrinsics.shape == (3, 3):
            intrinsics = np.broadcast_to(intrinsics, (frame_count, 3, 3))
        intrinsics_source = str(args.intrinsics)
    if intrinsics.shape != (frame_count, 3, 3):
        raise ValueError(
            f"Intrinsics must have shape (3,3) or ({frame_count},3,3), got {intrinsics.shape}"
        )
    if extrinsics.shape not in {(frame_count, 3, 4), (frame_count, 4, 4)}:
        raise ValueError(f"Unexpected extrinsics shape: {extrinsics.shape}")

    stride = args.pixel_stride
    confidence_threshold = None
    if args.confidence_percentile is not None:
        sampled_confidence = np.asarray(confidence[frames, ::stride, ::stride])
        finite_confidence = sampled_confidence[np.isfinite(sampled_confidence)]
        confidence_threshold = float(
            np.percentile(finite_confidence, args.confidence_percentile)
        )

    # Count first because binary PLY requires the vertex count in its header.
    point_count = 0
    for frame in frames:
        sampled_depth = np.asarray(depth[frame, ::stride, ::stride])
        sampled_conf = np.asarray(confidence[frame, ::stride, ::stride])
        point_count += int(
            valid_mask(
                sampled_depth, sampled_conf, confidence_threshold, args.max_depth
            ).sum()
        )
    if point_count == 0:
        raise ValueError("No valid points remain with the selected filters")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    camera_centers = []
    x_coordinates = np.arange(0, width, stride, dtype=np.float64)
    y_coordinates = np.arange(0, height, stride, dtype=np.float64)
    pixel_x, pixel_y = np.meshgrid(x_coordinates, y_coordinates)

    with args.output.open("wb") as handle:
        write_header(handle, point_count)
        points_written = 0
        for position, frame in enumerate(frames, start=1):
            sampled_depth = np.asarray(depth[frame, ::stride, ::stride])
            sampled_conf = np.asarray(confidence[frame, ::stride, ::stride])
            mask = valid_mask(
                sampled_depth, sampled_conf, confidence_threshold, args.max_depth
            )

            pixels = np.stack(
                [pixel_x[mask], pixel_y[mask], np.ones(int(mask.sum()))], axis=0
            )
            rays = np.linalg.inv(np.asarray(intrinsics[frame], dtype=np.float64)) @ pixels
            camera_points = rays * sampled_depth[mask][None, :]

            w2c = as_homogeneous(np.asarray(extrinsics[frame], dtype=np.float64))
            c2w = np.linalg.inv(w2c)
            camera_centers.append(c2w[:3, 3].copy())
            if args.camera_space:
                output_points = camera_points.T
            else:
                camera_h = np.vstack(
                    [camera_points, np.ones((1, camera_points.shape[1]), dtype=np.float64)]
                )
                output_points = (c2w @ camera_h)[:3].T

            colors = np.asarray(images[frame, ::stride, ::stride])[mask, :3]
            vertices = np.empty(output_points.shape[0], dtype=VERTEX_DTYPE)
            vertices["x"] = output_points[:, 0]
            vertices["y"] = output_points[:, 1]
            vertices["z"] = output_points[:, 2]
            vertices["red"] = colors[:, 0]
            vertices["green"] = colors[:, 1]
            vertices["blue"] = colors[:, 2]
            vertices.tofile(handle)
            points_written += len(vertices)
            print(
                f"Frame {frame:06d} ({position}/{len(frames)}): "
                f"{len(vertices):,} points"
            )

    if points_written != point_count:
        raise RuntimeError(f"Expected {point_count} points, wrote {points_written}")

    centers_path = args.output.with_suffix(".camera_centers.npy")
    np.save(centers_path, np.asarray(camera_centers, dtype=np.float32))
    metadata = {
        "output": str(args.output),
        "vertex_count": point_count,
        "frames": frames,
        "image_size_hw": [height, width],
        "pixel_stride": stride,
        "camera_space": args.camera_space,
        "confidence_percentile": args.confidence_percentile,
        "confidence_threshold": confidence_threshold,
        "max_depth": args.max_depth,
        "intrinsics_source": intrinsics_source,
        "extrinsics_convention": "DA3 OpenCV world-to-camera; inverted before world projection",
    }
    metadata_path = args.output.with_suffix(".json")
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n")

    print(f"Wrote {point_count:,} colored points to {args.output}")
    print(f"Wrote camera centers to {centers_path}")
    print(f"Wrote export metadata to {metadata_path}")


if __name__ == "__main__":
    main()
